version: "3.8"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: saksham12
      MYSQL_DATABASE: dav
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"  # Avoid 3306 if already in use

  backend:
    build: ./backend
    container_name: normalization-backend
    restart: always
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: saksham12
      DB_NAME: dav
    depends_on:
      - mysql-db
    ports:
      - "3000:3000"
